// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Detection {
  final BigInt classId;
  final String label;
  final double confidence;
  final UsizeArray4 bbox;
  final double validDepthRatio;
  final double? distanceM;
  final UsizeArray2? depthPoint;

  const Detection({
    required this.classId,
    required this.label,
    required this.confidence,
    required this.bbox,
    required this.validDepthRatio,
    this.distanceM,
    this.depthPoint,
  });

  @override
  int get hashCode =>
      classId.hashCode ^
      label.hashCode ^
      confidence.hashCode ^
      bbox.hashCode ^
      validDepthRatio.hashCode ^
      distanceM.hashCode ^
      depthPoint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Detection &&
          runtimeType == other.runtimeType &&
          classId == other.classId &&
          label == other.label &&
          confidence == other.confidence &&
          bbox == other.bbox &&
          validDepthRatio == other.validDepthRatio &&
          distanceM == other.distanceM &&
          depthPoint == other.depthPoint;
}

class Point {
  final String kind;
  final double x;
  final double y;
  final double distanceM;
  final String source;

  const Point({
    required this.kind,
    required this.x,
    required this.y,
    required this.distanceM,
    required this.source,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      x.hashCode ^
      y.hashCode ^
      distanceM.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          x == other.x &&
          y == other.y &&
          distanceM == other.distanceM &&
          source == other.source;
}

class Settings {
  final double minimumM;
  final double maximumM;
  final double confidence;
  final bool objectsOnly;

  const Settings({
    required this.minimumM,
    required this.maximumM,
    required this.confidence,
    required this.objectsOnly,
  });

  @override
  int get hashCode =>
      minimumM.hashCode ^
      maximumM.hashCode ^
      confidence.hashCode ^
      objectsOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          minimumM == other.minimumM &&
          maximumM == other.maximumM &&
          confidence == other.confidence &&
          objectsOnly == other.objectsOnly;
}
