// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'analysis.dart';
import 'calibration.dart';
import 'frb_generated.dart';
import 'lib.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `publish`, `state`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

Future<void> initialize({
  required String modelPath,
  required String runtimePath,
}) => RustLib.instance.api.crateApiInitialize(
  modelPath: modelPath,
  runtimePath: runtimePath,
);

Stream<String> subscribeResults() =>
    RustLib.instance.api.crateApiSubscribeResults();

Future<void> unsubscribeResults() =>
    RustLib.instance.api.crateApiUnsubscribeResults();

Future<void> startSession({required bool demo}) =>
    RustLib.instance.api.crateApiStartSession(demo: demo);

Future<void> stopSession() => RustLib.instance.api.crateApiStopSession();

Future<void> updateSettings({required String json}) =>
    RustLib.instance.api.crateApiUpdateSettings(json: json);

Future<double> loadCalibration({required String json}) =>
    RustLib.instance.api.crateApiLoadCalibration(json: json);

Future<double?> sampleDistance({required int x, required int y}) =>
    RustLib.instance.api.crateApiSampleDistance(x: x, y: y);

class FrameResult {
  final BigInt frameId;
  final BigInt timestampMs;
  final BigInt width;
  final BigInt height;
  final bool running;
  final bool demo;
  final double captureFps;
  final double depthFps;
  final double detectionFps;
  final double latencyMs;
  final List<Detection> detections;
  final List<Point> points;
  final List<String> warnings;
  final double? rms;
  final bool modelReady;

  const FrameResult({
    required this.frameId,
    required this.timestampMs,
    required this.width,
    required this.height,
    required this.running,
    required this.demo,
    required this.captureFps,
    required this.depthFps,
    required this.detectionFps,
    required this.latencyMs,
    required this.detections,
    required this.points,
    required this.warnings,
    this.rms,
    required this.modelReady,
  });

  static Future<FrameResult> default_() =>
      RustLib.instance.api.crateApiFrameResultDefault();

  @override
  int get hashCode =>
      frameId.hashCode ^
      timestampMs.hashCode ^
      width.hashCode ^
      height.hashCode ^
      running.hashCode ^
      demo.hashCode ^
      captureFps.hashCode ^
      depthFps.hashCode ^
      detectionFps.hashCode ^
      latencyMs.hashCode ^
      detections.hashCode ^
      points.hashCode ^
      warnings.hashCode ^
      rms.hashCode ^
      modelReady.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrameResult &&
          runtimeType == other.runtimeType &&
          frameId == other.frameId &&
          timestampMs == other.timestampMs &&
          width == other.width &&
          height == other.height &&
          running == other.running &&
          demo == other.demo &&
          captureFps == other.captureFps &&
          depthFps == other.depthFps &&
          detectionFps == other.detectionFps &&
          latencyMs == other.latencyMs &&
          detections == other.detections &&
          points == other.points &&
          warnings == other.warnings &&
          rms == other.rms &&
          modelReady == other.modelReady;
}

class State {
  final Settings settings;
  final Calibration? calibration;
  final bool running;
  final bool demo;
  final BigInt generation;
  final FrameResult result;
  final Float32List depth;
  final List<Uint8List> previews;
  final RustStreamSink<String>? sink;

  const State({
    required this.settings,
    this.calibration,
    required this.running,
    required this.demo,
    required this.generation,
    required this.result,
    required this.depth,
    required this.previews,
    this.sink,
  });

  static Future<State> default_() =>
      RustLib.instance.api.crateApiStateDefault();

  @override
  int get hashCode =>
      settings.hashCode ^
      calibration.hashCode ^
      running.hashCode ^
      demo.hashCode ^
      generation.hashCode ^
      result.hashCode ^
      depth.hashCode ^
      previews.hashCode ^
      sink.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is State &&
          runtimeType == other.runtimeType &&
          settings == other.settings &&
          calibration == other.calibration &&
          running == other.running &&
          demo == other.demo &&
          generation == other.generation &&
          result == other.result &&
          depth == other.depth &&
          previews == other.previews &&
          sink == other.sink;
}
