// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Calibration {
  final int schemaVersion;
  final String lengthUnit;
  final UsizeArray2 imageSize;
  final List<Float64List> leftCameraMatrix;
  final List<Float64List> rightCameraMatrix;
  final List<Float64List> leftDistortion;
  final List<Float64List> rightDistortion;
  final List<Float64List> rectificationLeft;
  final List<Float64List> rectificationRight;
  final List<Float64List> projectionLeft;
  final List<Float64List> projectionRight;
  final List<Float64List> rotation;
  final List<Float64List> translation;
  final List<Float64List> disparityToDepth;
  final double rmsStereo;

  const Calibration({
    required this.schemaVersion,
    required this.lengthUnit,
    required this.imageSize,
    required this.leftCameraMatrix,
    required this.rightCameraMatrix,
    required this.leftDistortion,
    required this.rightDistortion,
    required this.rectificationLeft,
    required this.rectificationRight,
    required this.projectionLeft,
    required this.projectionRight,
    required this.rotation,
    required this.translation,
    required this.disparityToDepth,
    required this.rmsStereo,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      lengthUnit.hashCode ^
      imageSize.hashCode ^
      leftCameraMatrix.hashCode ^
      rightCameraMatrix.hashCode ^
      leftDistortion.hashCode ^
      rightDistortion.hashCode ^
      rectificationLeft.hashCode ^
      rectificationRight.hashCode ^
      projectionLeft.hashCode ^
      projectionRight.hashCode ^
      rotation.hashCode ^
      translation.hashCode ^
      disparityToDepth.hashCode ^
      rmsStereo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Calibration &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          lengthUnit == other.lengthUnit &&
          imageSize == other.imageSize &&
          leftCameraMatrix == other.leftCameraMatrix &&
          rightCameraMatrix == other.rightCameraMatrix &&
          leftDistortion == other.leftDistortion &&
          rightDistortion == other.rightDistortion &&
          rectificationLeft == other.rectificationLeft &&
          rectificationRight == other.rectificationRight &&
          projectionLeft == other.projectionLeft &&
          projectionRight == other.projectionRight &&
          rotation == other.rotation &&
          translation == other.translation &&
          disparityToDepth == other.disparityToDepth &&
          rmsStereo == other.rmsStereo;
}
