// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'analysis.dart';
import 'api.dart';
import 'calibration.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1942750449;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'stereorange_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<FrameResult> crateApiFrameResultDefault();

  Future<void> crateApiInitApp();

  Future<void> crateApiInitialize({
    required String modelPath,
    required String runtimePath,
  });

  Future<double> crateApiLoadCalibration({required String json});

  Future<double?> crateApiSampleDistance({required int x, required int y});

  Future<void> crateApiStartSession({required bool demo});

  Future<State> crateApiStateDefault();

  Future<void> crateApiStopSession();

  Stream<String> crateApiSubscribeResults();

  Future<void> crateApiUnsubscribeResults();

  Future<void> crateApiUpdateSettings({required String json});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FrameResult> crateApiFrameResultDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_frame_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrameResultDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrameResultDefaultConstMeta =>
      const TaskConstMeta(debugName: "frame_result_default", argNames: []);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiInitialize({
    required String modelPath,
    required String runtimePath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(runtimePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitializeConstMeta,
        argValues: [modelPath, runtimePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitializeConstMeta => const TaskConstMeta(
    debugName: "initialize",
    argNames: ["modelPath", "runtimePath"],
  );

  @override
  Future<double> crateApiLoadCalibration({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLoadCalibrationConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadCalibrationConstMeta =>
      const TaskConstMeta(debugName: "load_calibration", argNames: ["json"]);

  @override
  Future<double?> crateApiSampleDistance({required int x, required int y}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(x, serializer);
          sse_encode_u_32(y, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_f_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSampleDistanceConstMeta,
        argValues: [x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSampleDistanceConstMeta =>
      const TaskConstMeta(debugName: "sample_distance", argNames: ["x", "y"]);

  @override
  Future<void> crateApiStartSession({required bool demo}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(demo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStartSessionConstMeta,
        argValues: [demo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartSessionConstMeta =>
      const TaskConstMeta(debugName: "start_session", argNames: ["demo"]);

  @override
  Future<State> crateApiStateDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_state,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStateDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStateDefaultConstMeta =>
      const TaskConstMeta(debugName: "state_default", argNames: []);

  @override
  Future<void> crateApiStopSession() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiStopSessionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopSessionConstMeta =>
      const TaskConstMeta(debugName: "stop_session", argNames: []);

  @override
  Stream<String> crateApiSubscribeResults() {
    final sink = RustStreamSink<String>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSubscribeResultsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSubscribeResultsConstMeta =>
      const TaskConstMeta(debugName: "subscribe_results", argNames: ["sink"]);

  @override
  Future<void> crateApiUnsubscribeResults() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUnsubscribeResultsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUnsubscribeResultsConstMeta =>
      const TaskConstMeta(debugName: "unsubscribe_results", argNames: []);

  @override
  Future<void> crateApiUpdateSettings({required String json}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(json, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpdateSettingsConstMeta,
        argValues: [json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpdateSettingsConstMeta =>
      const TaskConstMeta(debugName: "update_settings", argNames: ["json"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Calibration dco_decode_box_autoadd_calibration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_calibration(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  Calibration dco_decode_calibration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return Calibration(
      schemaVersion: dco_decode_u_32(arr[0]),
      lengthUnit: dco_decode_String(arr[1]),
      imageSize: dco_decode_usize_array_2(arr[2]),
      leftCameraMatrix: dco_decode_list_list_prim_f_64_strict(arr[3]),
      rightCameraMatrix: dco_decode_list_list_prim_f_64_strict(arr[4]),
      leftDistortion: dco_decode_list_list_prim_f_64_strict(arr[5]),
      rightDistortion: dco_decode_list_list_prim_f_64_strict(arr[6]),
      rectificationLeft: dco_decode_list_list_prim_f_64_strict(arr[7]),
      rectificationRight: dco_decode_list_list_prim_f_64_strict(arr[8]),
      projectionLeft: dco_decode_list_list_prim_f_64_strict(arr[9]),
      projectionRight: dco_decode_list_list_prim_f_64_strict(arr[10]),
      rotation: dco_decode_list_list_prim_f_64_strict(arr[11]),
      translation: dco_decode_list_list_prim_f_64_strict(arr[12]),
      disparityToDepth: dco_decode_list_list_prim_f_64_strict(arr[13]),
      rmsStereo: dco_decode_f_64(arr[14]),
    );
  }

  @protected
  Detection dco_decode_detection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Detection(
      classId: dco_decode_usize(arr[0]),
      label: dco_decode_String(arr[1]),
      confidence: dco_decode_f_32(arr[2]),
      bbox: dco_decode_usize_array_4(arr[3]),
      validDepthRatio: dco_decode_f_32(arr[4]),
      distanceM: dco_decode_opt_box_autoadd_f_32(arr[5]),
      depthPoint: dco_decode_opt_usize_array_2(arr[6]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FrameResult dco_decode_frame_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return FrameResult(
      frameId: dco_decode_u_64(arr[0]),
      timestampMs: dco_decode_u_64(arr[1]),
      width: dco_decode_usize(arr[2]),
      height: dco_decode_usize(arr[3]),
      running: dco_decode_bool(arr[4]),
      demo: dco_decode_bool(arr[5]),
      captureFps: dco_decode_f_32(arr[6]),
      depthFps: dco_decode_f_32(arr[7]),
      detectionFps: dco_decode_f_32(arr[8]),
      latencyMs: dco_decode_f_32(arr[9]),
      detections: dco_decode_list_detection(arr[10]),
      points: dco_decode_list_point(arr[11]),
      warnings: dco_decode_list_String(arr[12]),
      rms: dco_decode_opt_box_autoadd_f_64(arr[13]),
      modelReady: dco_decode_bool(arr[14]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Detection> dco_decode_list_detection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_detection).toList();
  }

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_f_64_strict)
        .toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<Point> dco_decode_list_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_point).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint64List;
  }

  @protected
  RustStreamSink<String>? dco_decode_opt_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_StreamSink_String_Sse(raw);
  }

  @protected
  Calibration? dco_decode_opt_box_autoadd_calibration(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_calibration(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  UsizeArray2? dco_decode_opt_usize_array_2(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_usize_array_2(raw);
  }

  @protected
  Point dco_decode_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Point(
      kind: dco_decode_String(arr[0]),
      x: dco_decode_f_32(arr[1]),
      y: dco_decode_f_32(arr[2]),
      distanceM: dco_decode_f_32(arr[3]),
      source: dco_decode_String(arr[4]),
    );
  }

  @protected
  Settings dco_decode_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return Settings(
      minimumM: dco_decode_f_32(arr[0]),
      maximumM: dco_decode_f_32(arr[1]),
      confidence: dco_decode_f_32(arr[2]),
      objectsOnly: dco_decode_bool(arr[3]),
    );
  }

  @protected
  State dco_decode_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return State(
      settings: dco_decode_settings(arr[0]),
      calibration: dco_decode_opt_box_autoadd_calibration(arr[1]),
      running: dco_decode_bool(arr[2]),
      demo: dco_decode_bool(arr[3]),
      generation: dco_decode_u_64(arr[4]),
      result: dco_decode_frame_result(arr[5]),
      depth: dco_decode_list_prim_f_32_strict(arr[6]),
      previews: dco_decode_list_list_prim_u_8_strict(arr[7]),
      sink: dco_decode_opt_StreamSink_String_Sse(arr[8]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  UsizeArray2 dco_decode_usize_array_2(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UsizeArray2(dco_decode_list_prim_usize_strict(raw));
  }

  @protected
  UsizeArray4 dco_decode_usize_array_4(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UsizeArray4(dco_decode_list_prim_usize_strict(raw));
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Calibration sse_decode_box_autoadd_calibration(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_calibration(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  Calibration sse_decode_calibration(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_schemaVersion = sse_decode_u_32(deserializer);
    var var_lengthUnit = sse_decode_String(deserializer);
    var var_imageSize = sse_decode_usize_array_2(deserializer);
    var var_leftCameraMatrix = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_rightCameraMatrix = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_leftDistortion = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_rightDistortion = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_rectificationLeft = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_rectificationRight = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_projectionLeft = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_projectionRight = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_rotation = sse_decode_list_list_prim_f_64_strict(deserializer);
    var var_translation = sse_decode_list_list_prim_f_64_strict(deserializer);
    var var_disparityToDepth = sse_decode_list_list_prim_f_64_strict(
      deserializer,
    );
    var var_rmsStereo = sse_decode_f_64(deserializer);
    return Calibration(
      schemaVersion: var_schemaVersion,
      lengthUnit: var_lengthUnit,
      imageSize: var_imageSize,
      leftCameraMatrix: var_leftCameraMatrix,
      rightCameraMatrix: var_rightCameraMatrix,
      leftDistortion: var_leftDistortion,
      rightDistortion: var_rightDistortion,
      rectificationLeft: var_rectificationLeft,
      rectificationRight: var_rectificationRight,
      projectionLeft: var_projectionLeft,
      projectionRight: var_projectionRight,
      rotation: var_rotation,
      translation: var_translation,
      disparityToDepth: var_disparityToDepth,
      rmsStereo: var_rmsStereo,
    );
  }

  @protected
  Detection sse_decode_detection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_classId = sse_decode_usize(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    var var_bbox = sse_decode_usize_array_4(deserializer);
    var var_validDepthRatio = sse_decode_f_32(deserializer);
    var var_distanceM = sse_decode_opt_box_autoadd_f_32(deserializer);
    var var_depthPoint = sse_decode_opt_usize_array_2(deserializer);
    return Detection(
      classId: var_classId,
      label: var_label,
      confidence: var_confidence,
      bbox: var_bbox,
      validDepthRatio: var_validDepthRatio,
      distanceM: var_distanceM,
      depthPoint: var_depthPoint,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FrameResult sse_decode_frame_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_frameId = sse_decode_u_64(deserializer);
    var var_timestampMs = sse_decode_u_64(deserializer);
    var var_width = sse_decode_usize(deserializer);
    var var_height = sse_decode_usize(deserializer);
    var var_running = sse_decode_bool(deserializer);
    var var_demo = sse_decode_bool(deserializer);
    var var_captureFps = sse_decode_f_32(deserializer);
    var var_depthFps = sse_decode_f_32(deserializer);
    var var_detectionFps = sse_decode_f_32(deserializer);
    var var_latencyMs = sse_decode_f_32(deserializer);
    var var_detections = sse_decode_list_detection(deserializer);
    var var_points = sse_decode_list_point(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    var var_rms = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_modelReady = sse_decode_bool(deserializer);
    return FrameResult(
      frameId: var_frameId,
      timestampMs: var_timestampMs,
      width: var_width,
      height: var_height,
      running: var_running,
      demo: var_demo,
      captureFps: var_captureFps,
      depthFps: var_depthFps,
      detectionFps: var_detectionFps,
      latencyMs: var_latencyMs,
      detections: var_detections,
      points: var_points,
      warnings: var_warnings,
      rms: var_rms,
      modelReady: var_modelReady,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Detection> sse_decode_list_detection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Detection>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_detection(deserializer));
    }
    return ans_;
  }

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Float64List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_f_64_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<Point> sse_decode_list_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Point>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_point(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  RustStreamSink<String>? sse_decode_opt_StreamSink_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_StreamSink_String_Sse(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Calibration? sse_decode_opt_box_autoadd_calibration(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_calibration(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  UsizeArray2? sse_decode_opt_usize_array_2(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_usize_array_2(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Point sse_decode_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    var var_distanceM = sse_decode_f_32(deserializer);
    var var_source = sse_decode_String(deserializer);
    return Point(
      kind: var_kind,
      x: var_x,
      y: var_y,
      distanceM: var_distanceM,
      source: var_source,
    );
  }

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_minimumM = sse_decode_f_32(deserializer);
    var var_maximumM = sse_decode_f_32(deserializer);
    var var_confidence = sse_decode_f_32(deserializer);
    var var_objectsOnly = sse_decode_bool(deserializer);
    return Settings(
      minimumM: var_minimumM,
      maximumM: var_maximumM,
      confidence: var_confidence,
      objectsOnly: var_objectsOnly,
    );
  }

  @protected
  State sse_decode_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_settings = sse_decode_settings(deserializer);
    var var_calibration = sse_decode_opt_box_autoadd_calibration(deserializer);
    var var_running = sse_decode_bool(deserializer);
    var var_demo = sse_decode_bool(deserializer);
    var var_generation = sse_decode_u_64(deserializer);
    var var_result = sse_decode_frame_result(deserializer);
    var var_depth = sse_decode_list_prim_f_32_strict(deserializer);
    var var_previews = sse_decode_list_list_prim_u_8_strict(deserializer);
    var var_sink = sse_decode_opt_StreamSink_String_Sse(deserializer);
    return State(
      settings: var_settings,
      calibration: var_calibration,
      running: var_running,
      demo: var_demo,
      generation: var_generation,
      result: var_result,
      depth: var_depth,
      previews: var_previews,
      sink: var_sink,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  UsizeArray2 sse_decode_usize_array_2(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_usize_strict(deserializer);
    return UsizeArray2(inner);
  }

  @protected
  UsizeArray4 sse_decode_usize_array_4(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_usize_strict(deserializer);
    return UsizeArray4(inner);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
    RustStreamSink<String> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_calibration(
    Calibration self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_calibration(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_calibration(Calibration self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.schemaVersion, serializer);
    sse_encode_String(self.lengthUnit, serializer);
    sse_encode_usize_array_2(self.imageSize, serializer);
    sse_encode_list_list_prim_f_64_strict(self.leftCameraMatrix, serializer);
    sse_encode_list_list_prim_f_64_strict(self.rightCameraMatrix, serializer);
    sse_encode_list_list_prim_f_64_strict(self.leftDistortion, serializer);
    sse_encode_list_list_prim_f_64_strict(self.rightDistortion, serializer);
    sse_encode_list_list_prim_f_64_strict(self.rectificationLeft, serializer);
    sse_encode_list_list_prim_f_64_strict(self.rectificationRight, serializer);
    sse_encode_list_list_prim_f_64_strict(self.projectionLeft, serializer);
    sse_encode_list_list_prim_f_64_strict(self.projectionRight, serializer);
    sse_encode_list_list_prim_f_64_strict(self.rotation, serializer);
    sse_encode_list_list_prim_f_64_strict(self.translation, serializer);
    sse_encode_list_list_prim_f_64_strict(self.disparityToDepth, serializer);
    sse_encode_f_64(self.rmsStereo, serializer);
  }

  @protected
  void sse_encode_detection(Detection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.classId, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_f_32(self.confidence, serializer);
    sse_encode_usize_array_4(self.bbox, serializer);
    sse_encode_f_32(self.validDepthRatio, serializer);
    sse_encode_opt_box_autoadd_f_32(self.distanceM, serializer);
    sse_encode_opt_usize_array_2(self.depthPoint, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_frame_result(FrameResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.frameId, serializer);
    sse_encode_u_64(self.timestampMs, serializer);
    sse_encode_usize(self.width, serializer);
    sse_encode_usize(self.height, serializer);
    sse_encode_bool(self.running, serializer);
    sse_encode_bool(self.demo, serializer);
    sse_encode_f_32(self.captureFps, serializer);
    sse_encode_f_32(self.depthFps, serializer);
    sse_encode_f_32(self.detectionFps, serializer);
    sse_encode_f_32(self.latencyMs, serializer);
    sse_encode_list_detection(self.detections, serializer);
    sse_encode_list_point(self.points, serializer);
    sse_encode_list_String(self.warnings, serializer);
    sse_encode_opt_box_autoadd_f_64(self.rms, serializer);
    sse_encode_bool(self.modelReady, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_detection(
    List<Detection> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_detection(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_f_64_strict(
    List<Float64List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_f_64_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_point(List<Point> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_opt_StreamSink_String_Sse(
    RustStreamSink<String>? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_StreamSink_String_Sse(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_calibration(
    Calibration? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_calibration(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_usize_array_2(
    UsizeArray2? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_usize_array_2(self, serializer);
    }
  }

  @protected
  void sse_encode_point(Point self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
    sse_encode_f_32(self.distanceM, serializer);
    sse_encode_String(self.source, serializer);
  }

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.minimumM, serializer);
    sse_encode_f_32(self.maximumM, serializer);
    sse_encode_f_32(self.confidence, serializer);
    sse_encode_bool(self.objectsOnly, serializer);
  }

  @protected
  void sse_encode_state(State self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings(self.settings, serializer);
    sse_encode_opt_box_autoadd_calibration(self.calibration, serializer);
    sse_encode_bool(self.running, serializer);
    sse_encode_bool(self.demo, serializer);
    sse_encode_u_64(self.generation, serializer);
    sse_encode_frame_result(self.result, serializer);
    sse_encode_list_prim_f_32_strict(self.depth, serializer);
    sse_encode_list_list_prim_u_8_strict(self.previews, serializer);
    sse_encode_opt_StreamSink_String_Sse(self.sink, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_usize_array_2(UsizeArray2 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_usize_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_usize_array_4(UsizeArray4 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_usize_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
